name: release
on:
  push:
    tags:
      - "v*"
permissions:
  contents: write
  id-token: write
  attestations: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cli/gh-extension-precompile@bagtoad/50-error-androidamd64-requires-external-cgo-linking-but-cgo-is-not-enabled
        with:
          release_android: true
          android_sdk_version: 30
          generate_attestations: true
          go_version_file: go.mod
